In [3]:
%matplotlib inline
from fns import *
from syntheticdata import synthetic_generation
# import ipyvolume

In [4]:
import plotly
plotly.tools.set_credentials_file(username='gpernelle', api_key='4KIdNJBBApIeebdKxyN9')
import plotly.plotly as py
import plotly.graph_objs as go


In [5]:
def dice(logits, labels):
        flat_logits = logits.flatten()
        flat_labels = labels.flatten()
        intersection = np.sum(flat_logits*flat_labels)
        union = np.sum(flat_logits) + np.sum(flat_labels)
        loss = 1 - 2 * intersection / union
        return loss

### Predict

In [24]:
def predict_case(caseNumber):
    case=str(caseNumber)
    image_name = '/home/gp1514/SSD/preprocessed_data/LabelMapsNEW2_1.00-1.00-1.00_split2/%s/case.nrrd'%case
    label_name = '/home/gp1514/SSD/preprocessed_data/LabelMapsNEW2_1.00-1.00-1.00/%s/needles.nrrd'%case

    data, options_ = nrrd.read(image_name)
    data = data.astype(np.float32)
    data1, options = nrrd.read(image_name.replace('_split2', ''))
    data1 = data1.astype(np.float32)

    label_data, options_ = nrrd.read(label_name)

    prediction = predict([data1,data], "./models/unet_trained_mix_dropout-05-clahe30_f32")
    return label_data, prediction, options


def save_case(caseNumber):
    case=str(caseNumber)
    image_name = '/home/gp1514/SSD/preprocessed_data/LabelMapsNEW2_1.00-1.00-1.00_split2/%s/case.nrrd'%case
    data1, options = nrrd.read(image_name.replace('_split2', ''))
    data1 = data1.astype(np.float32)
    nrrd.write('predictions/case_%s.nrrd'%str(caseNumber), data1, options=options)



In [18]:
def predict_and_save(caseNumber):
    label_data, prediction, options = predict_case(caseNumber)
    dice(prediction, label_data)
    islands = post_processing(prediction, min_area=int(50), max_residual=float(4))
    nrrd.write('predictions/%s.nrrd'%str(caseNumber), islands, options=options)

def predict_and_plot3d(caseNumber):
    label_data, prediction, options = predict_case(caseNumber)
    dice(prediction, label_data)
    islands = post_processing(prediction, min_area=int(50), max_residual=float(4))
    nrrd.write('predictions/%s.nrrd'%str(caseNumber), islands, options=options)
    x,y,z = np.where(label_data == 1)
    xs,ys,zs = np.where(islands != 0)

    trace1 = go.Scatter3d(
        x=x,
        y=y,
        z=z,
        mode='markers',
        marker=dict(
            size=3,
            line=dict(
                color='green',
                width=2
            ),
            opacity=0.3
        )
    )

    trace2 = go.Scatter3d(
        x=xs,
        y=ys,
        z=zs,
        mode='markers',
        marker=dict(
            color='red',
            size=3,
            symbol='circle',
            line=dict(
                color='rgb(204, 204, 204)',
                width=1
            ),
            opacity=0.3
        )
    )
    data = [trace1, trace2]
    layout = go.Layout(
        margin=dict(
            l=0,
            r=0,
            b=0,
            t=0
        )
    )

    fig = go.Figure(data=data, layout=layout)
    py.iplot(fig, filename='simple-3d-scatter')

In [8]:
validationCases = loadCases("preprocessing/validation.txt")
testingCases = loadCases("preprocessing/testing.txt")

In [9]:
validationCases

['021', '023', '037', '038', '070', '071', '072', '074', '075', '076', '077']

In [10]:
testingCases

['028', '051', '054']

In [15]:
for case in validationCases:
    predict_and_save(case)

--------------------------------------------------
Loading and Preparing the data
Original input shape (200, 200, 77)
Padded input shape: (288, 288, 165)
# of parts 5 5 3
number of tiles: 75 
data shape (75, 148, 148, 148)
Original input shape (200, 200, 77)
Padded input shape: (288, 288, 165)
# of parts 5 5 3
number of tiles: 75 
data shape (75, 148, 148, 148)


100%|██████████| 75/75 [00:00<00:00, 639375.61it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (75, 148, 148, 148, 2)
Feature shape:  (75, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 3.cpkt


100%|██████████| 75/75 [00:32<00:00,  2.61it/s]


prediction shape: (75, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (288, 288, 165)
# of parts 5 5 3
# of subvolumes merged:  75
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15], dtype=uint16), array([3077040,    1085,     613,     832,     103,      45,      41,
            46,      51,      37,      35,      27,      15,      18,
             5,       7]))
(200, 200, 77)
Number of regions: 18
1 1.03882356434 118
2 1.14661786773 241
3 1.12693186823 202
4 1.17225105284 193
5 1.07417868319 157
6 1.1670551589 147
7 1.06904409815 106
8 1.04412159822 163
9 1.64221277971 232
--------------------------------------------------
Loading and Preparing the data
Original input shape (200, 200, 240)
Padded input shape: (288, 288, 328)
# of parts 5 5 6
number of tiles: 125 
data shape (125, 148, 148, 148)
Original input shape (200, 200, 240)
Padded input shape: (288, 288, 328)
# of parts 5 5 6
number of tiles: 125 

100%|██████████| 125/125 [00:00<00:00, 787219.22it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (125, 148, 148, 148, 2)
Feature shape:  (125, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 3.cpkt


100%|██████████| 125/125 [00:51<00:00,  2.53it/s]


prediction shape: (125, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (288, 288, 328)
# of parts 5 5 6
# of subvolumes merged:  125
(array([0, 1, 2, 3], dtype=uint16), array([9587203,   11508,    1112,     177]))
(200, 200, 240)
Number of regions: 62
1 3.73389990529 1563
2 1.14351180286 250
3 1.01814572583 93
4 1.14415810746 76
5 1.1101837314 163
6 1.0594522935 106
7 0.94956822085 65
8 0.96360935794 57
9 2.24505963343 624
10 1.01846418015 81
11 1.08364005714 172
12 1.12620933089 340
13 0.956561978922 95
14 1.10292467103 267
15 1.08082632405 281
16 2.00833530863 1120
17 1.22247704313 180
18 1.11469843032 172
19 2.54912547713 307
20 1.03951256196 270
21 2.3253252079 1313
22 1.07836258105 242
23 1.56501527859 390
24 1.73132786814 913
25 2.90779949179 1614
26 1.1339460438 315
27 1.04535165401 192
28 1.17921122557 123
29 1.07720819737 255
30 1.57315283909 527
31 1.47902579814 95
32 1.59269499952 177
33 1.16078658587 51
----------

100%|██████████| 96/96 [00:00<00:00, 738813.18it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (96, 148, 148, 148, 2)
Feature shape:  (96, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 3.cpkt


100%|██████████| 96/96 [00:38<00:00,  2.47it/s]


prediction shape: (96, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 241)
# of parts 7 7 5
# of subvolumes merged:  96
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=uint16), array([8941983,    4305,    1172,    1662,     249,     202,     202,
           153,     204,     202,     134,      25,       7]))
(300, 195, 153)
Number of regions: 48
1 1.0248624473 115
2 1.01406675859 165
3 1.06542989086 227
4 1.13878930651 605
5 1.14494475354 265
6 1.13942349763 709
7 1.14880171221 585
8 1.10890893225 625
9 1.16072924923 182
10 1.11390420992 171
11 1.07355643392 111
12 1.15313685574 180
13 1.05077275914 129
14 1.00471152815 238
15 1.34465075367 242
16 1.11554858529 208
17 1.17976290785 211
18 1.07368013632 118
19 1.94075435208 157
20 2.47627775797 265
21 1.40231249608 65
--------------------------------------------------
Loading and Preparing the data
Original input shape (319, 319, 128)
Padded input

100%|██████████| 147/147 [00:00<00:00, 934185.89it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (147, 148, 148, 148, 2)
Feature shape:  (147, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 4.cpkt


100%|██████████| 147/147 [00:59<00:00,  2.55it/s]


prediction shape: (147, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (407, 407, 216)
# of parts 7 7 4
# of subvolumes merged:  147
(array([0, 1, 2, 3, 4], dtype=uint16), array([13009135,     9308,     4967,     1109,      889]))
(319, 319, 128)
Number of regions: 40
1 1.20067954788 963
2 1.19040008856 945
3 1.05931341431 137
4 3.17504569928 1939
5 1.13112702008 861
6 1.13910333935 789
7 1.00043361477 86
8 1.79564429612 1112
9 1.31289078007 187
10 1.08723023316 173
11 1.82258435378 335
12 1.04401532938 142
13 1.36479709602 926
14 1.00942520273 65
15 3.47138634617 649
16 1.00319158294 51
17 1.19279608884 65
--------------------------------------------------
Loading and Preparing the data
Original input shape (300, 195, 230)
Padded input shape: (388, 283, 318)
# of parts 7 7 6
number of tiles: 120 
data shape (120, 148, 148, 148)
Original input shape (300, 195, 230)
Padded input shape: (388, 283, 318)
# of parts 7 7 6
number o

100%|██████████| 120/120 [00:00<00:00, 186137.75it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (120, 148, 148, 148, 2)
Feature shape:  (120, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 4.cpkt


100%|██████████| 120/120 [00:46<00:00,  2.57it/s]


prediction shape: (120, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 318)
# of parts 7 7 6
# of subvolumes merged:  120
(array([0, 1, 2, 3], dtype=uint16), array([13439814,    14821,      318,       47]))
(300, 195, 230)
Number of regions: 55
1 0.97212478627 90
2 0.932433579914 52
3 1.14328129879 205
4 1.03122485519 126
5 1.15306061201 748
6 1.1279032769 625
7 1.36689280679 989
8 1.15378371291 333
9 1.11323860841 375
10 1.11581782567 350
11 1.11712885919 265
12 1.14170736998 159
13 1.14472248712 180
14 1.02605075546 183
15 1.61884222639 363
16 1.11495137882 905
17 1.10148974438 176
18 1.14302590399 433
19 1.25512741114 1005
20 0.979761850095 67
21 0.972674455346 72
22 1.12266865729 347
23 2.90440594733 309
--------------------------------------------------
Loading and Preparing the data
Original input shape (300, 195, 230)
Padded input shape: (388, 283, 318)
# of parts 7 7 6
number of tiles: 120 
data shape (120,

100%|██████████| 120/120 [00:00<00:00, 869285.80it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (120, 148, 148, 148, 2)
Feature shape:  (120, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 4.cpkt


100%|██████████| 120/120 [00:46<00:00,  2.54it/s]


prediction shape: (120, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 318)
# of parts 7 7 6
# of subvolumes merged:  120
(array([0, 1, 2, 3, 4, 5, 6], dtype=uint16), array([13428190,    19374,     6692,      389,      167,      132,       56]))
(300, 195, 230)
Number of regions: 87
1 1.30929859138 60
2 0.933493815787 57
3 0.920058052235 67
4 1.10363295902 850
5 1.13970772983 965
6 2.85281228818 1872
7 1.15520428563 879
8 0.998309459623 87
9 0.978788649827 95
10 1.08166702612 237
11 1.13722916086 313
12 1.15486206836 328
13 1.32575089728 373
14 1.01348090455 73
15 1.1290230054 597
16 1.15385121725 304
17 1.17766816344 1046
18 1.16981447916 382
19 1.03004661306 60
20 1.12975674411 72
21 1.14140549009 946
22 1.10266476431 624
23 1.1038642623 638
24 1.64160959109 235
25 2.09365174548 339
26 1.18614624161 275
27 0.984458785111 82
28 1.01244518246 73
29 2.59411394511 349
-------------------------------------------------

100%|██████████| 96/96 [00:00<00:00, 675592.59it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (96, 148, 148, 148, 2)
Feature shape:  (96, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 4.cpkt


100%|██████████| 96/96 [00:39<00:00,  2.49it/s]


prediction shape: (96, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 280)
# of parts 7 7 5
# of subvolumes merged:  96
(array([0, 1, 2, 3, 4, 5, 6], dtype=uint16), array([11207126,    17095,     6884,      362,      481,       26,       26]))
(300, 195, 192)
Number of regions: 55
1 1.06266773537 209
2 1.15575771226 207
3 1.12098408827 152
4 1.1176558295 111
5 3.80791237244 2473
6 1.14572473868 871
7 1.12697814581 804
8 1.02353741846 113
9 1.16531583788 899
10 1.46531502822 869
11 1.03367001511 97
12 1.15962149299 964
13 1.15114480222 432
14 1.03186310196 55
15 1.09078701084 121
16 1.14177862136 504
17 2.08438482513 1141
18 1.14063773735 374
19 1.12224597418 1009
20 1.12234545422 430
21 1.06515293323 70
22 1.0957780534 265
23 1.18274806769 504
24 1.15183321011 1018
25 1.16226576449 885
26 1.16526271831 605
27 1.06059803331 190
28 1.11643114908 755
29 1.13423587694 883
30 1.14364400425 878
31 1.09769771295 782
32 1.

100%|██████████| 120/120 [00:00<00:00, 354698.01it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (120, 148, 148, 148, 2)
Feature shape:  (120, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 4.cpkt


100%|██████████| 120/120 [00:48<00:00,  2.58it/s]


prediction shape: (120, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 292)
# of parts 7 7 5
# of subvolumes merged:  120
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=uint16), array([11915326,    12177,     3705,     1840,      190,      114,
            147,      176,      198,       91,       30,        6]))
(300, 195, 204)
Number of regions: 196
1 1.51878846734 210
2 0.978228305124 60
3 1.00639212396 91
4 1.48396145948 390
5 1.01619817347 97
6 1.44006892416 195
7 0.871333428868 58
8 1.71315872421 264
9 1.08694154891 111
10 1.1208321981 216
11 1.1247589501 201
12 1.07645236928 143
13 1.1993353979 926
14 1.138625528 73
15 1.07878842529 275
16 1.10375120239 95
17 1.18454637278 353
18 1.15244082231 433
19 0.90388768243 57
20 1.09460904994 266
21 1.01387839123 56
22 1.06255331968 201
23 1.0511163794 427
24 1.02774415638 239
25 0.943166920527 63
26 1.09377968088 308
27 1.21331499806 451
28 1.11179511

100%|██████████| 96/96 [00:00<00:00, 761159.14it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (96, 148, 148, 148, 2)
Feature shape:  (96, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 4.cpkt


100%|██████████| 96/96 [00:36<00:00,  2.55it/s]


prediction shape: (96, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 267)
# of parts 7 7 5
# of subvolumes merged:  96
(array([0, 1, 2, 3], dtype=uint16), array([10463793,     6376,     1287,       44]))
(300, 195, 179)
Number of regions: 35
1 1.02334708534 153
2 1.00581173292 98
3 0.973794034472 58
4 1.00086846344 94
5 1.22165731201 686
6 1.1208292246 826
7 1.23658469983 193
8 1.03380132658 115
9 2.44964022432 1277
10 2.64015613684 1865
11 2.36298170596 1813
12 1.0146393675 100
--------------------------------------------------
Loading and Preparing the data
Original input shape (300, 195, 179)
Padded input shape: (388, 283, 267)
# of parts 7 7 5
number of tiles: 96 
data shape (96, 148, 148, 148)
Original input shape (300, 195, 179)
Padded input shape: (388, 283, 267)
# of parts 7 7 5
number of tiles: 96 
data shape (96, 148, 148, 148)


100%|██████████| 96/96 [00:00<00:00, 439577.71it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (96, 148, 148, 148, 2)
Feature shape:  (96, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 4.cpkt


100%|██████████| 96/96 [00:40<00:00,  1.87it/s]


prediction shape: (96, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 267)
# of parts 7 7 5
# of subvolumes merged:  96
(array([0, 1, 2, 3, 4, 5, 6], dtype=uint16), array([10454426,    11042,     5486,      115,      373,       17,       41]))
(300, 195, 179)
Number of regions: 76
1 2.15762588459 282
2 1.02863046525 59
3 1.07742430347 52
4 1.74647583453 233
5 1.94559309858 476
6 1.41527831842 130
7 0.997369570728 55
8 0.971488500001 78
9 0.928392132038 88
10 3.80449469443 2079
11 3.51122551938 2292
12 1.13172196616 167
13 3.99629934262 2692
14 1.11806446109 116
15 1.03634567856 156
16 1.16762302012 155
17 1.77209306286 306
18 1.15825461856 144
19 1.16727554843 144
20 2.03964434024 988
21 1.09449699079 316
22 1.01313597674 100
23 1.31794379384 1192
24 0.945860949197 59
25 1.12477306434 277
26 1.05388180602 198
27 0.958062703093 65
28 1.03395390851 256
29 0.996891967061 155
-------------------------------------------

100%|██████████| 96/96 [00:00<00:00, 958698.06it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (96, 148, 148, 148, 2)
Feature shape:  (96, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 4.cpkt


100%|██████████| 96/96 [00:37<00:00,  2.32it/s]


prediction shape: (96, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 254)
# of parts 7 7 5
# of subvolumes merged:  96
(array([0, 1, 2, 3, 4], dtype=uint16), array([9702724,    6109,    1808,     303,      56]))
(300, 195, 166)
Number of regions: 46
1 0.900571086929 53
2 1.12641023453 77
3 0.943084434411 91
4 0.98832450191 66
5 1.09172542506 274
6 1.34124100697 172
7 1.85746295917 366
8 1.06043336577 129
9 1.02879602786 111
10 1.05943386723 344
11 1.09712349491 438
12 3.03748097232 857
13 0.958126135094 66
14 1.131542999 574
15 1.10704701568 522
16 0.923792173739 68
17 0.998394391793 110
18 1.07250946042 103
19 1.12413642399 61


In [16]:
for case in testingCases:
    predict_and_save(case)

--------------------------------------------------
Loading and Preparing the data
Original input shape (220, 220, 204)
Padded input shape: (308, 308, 292)
# of parts 6 6 5
number of tiles: 125 
data shape (125, 148, 148, 148)
Original input shape (220, 220, 204)
Padded input shape: (308, 308, 292)
# of parts 6 6 5
number of tiles: 125 
data shape (125, 148, 148, 148)


100%|██████████| 125/125 [00:00<00:00, 825650.39it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (125, 148, 148, 148, 2)
Feature shape:  (125, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 5.cpkt


100%|██████████| 125/125 [00:56<00:00,  2.50it/s]


prediction shape: (125, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (308, 308, 292)
# of parts 6 6 5
# of subvolumes merged:  125
(array([0, 1, 2, 3, 4, 5, 6], dtype=uint16), array([9847801,   21688,    2651,    1436,      21,       2,       1]))
(220, 220, 204)
Number of regions: 95
1 2.38153956868 381
2 1.093609769 273
3 1.1228390753 212
4 1.13250899646 354
5 1.25116053618 814
6 1.07114313448 317
7 1.1181439722 192
8 1.24653381678 228
9 1.08702711799 776
10 1.72090621128 1207
11 1.09295215791 375
12 1.20499343663 1107
13 1.11291849487 362
14 1.08349993003 445
15 1.03702757345 160
16 1.12289795898 398
17 1.12680020226 692
18 2.28234143434 1233
19 2.80049928738 840
20 1.11545556484 811
21 1.67531219544 704
22 1.24011093843 938
23 1.21915449635 115
24 1.15467514923 1156
25 0.94662267129 79
26 2.71464288086 1396
27 1.12917407491 112
28 1.08665784329 70
29 1.13586822945 702
30 1.10940461747 1050
31 2.59732949841 2336
32 1.020

100%|██████████| 96/96 [00:00<00:00, 131543.02it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (96, 148, 148, 148, 2)
Feature shape:  (96, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 5.cpkt


100%|██████████| 96/96 [00:42<00:00,  2.57it/s]


prediction shape: (96, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 279)
# of parts 7 7 5
# of subvolumes merged:  96
(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=uint16), array([11158612,     8700,     2678,     1089,     2254,       94,
             38,       26,        9]))
(300, 195, 191)
Number of regions: 43
1 1.12683864877 153
2 0.914007488551 93
3 1.35710348167 474
4 0.989136649154 64
5 1.11355326443 620
6 1.08622545468 574
7 1.07895610794 444
8 1.00882147404 76
9 1.06264432326 126
10 1.11084522808 196
11 1.34581191833 110
12 1.05179604345 61
13 1.08288343321 110
14 1.00166375313 86
15 2.8502815031 1815
16 1.12036773585 802
17 1.11824762619 805
18 1.17280033792 766
19 1.07847369018 828
20 0.948846526053 67
21 1.02577706719 113
--------------------------------------------------
Loading and Preparing the data
Original input shape (319, 319, 220)
Padded input shape: (407, 407, 308)
# of parts 7 7 6
number of ti

100%|██████████| 245/245 [00:00<00:00, 1102579.91it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (245, 148, 148, 148, 2)
Feature shape:  (245, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 5.cpkt


100%|██████████| 245/245 [01:40<00:00,  2.59it/s]


prediction shape: (245, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (407, 407, 308)
# of parts 7 7 6
# of subvolumes merged:  245
(array([0, 1, 2, 3], dtype=uint16), array([22377834,     9440,       36,      110]))
(319, 319, 220)
Number of regions: 35
1 2.75415777664 440
2 0.958465043059 74
3 1.05409727428 190
4 1.01509114766 132
5 2.16910435777 1096
6 1.12314136338 333
7 1.07016822832 134
8 1.07382002294 137
9 1.00608888793 95
10 1.10937917918 582
11 1.06624199159 119
12 1.09510772297 619
13 0.964160450633 64
14 1.12418258231 683
15 1.10125371609 736
16 1.15520018706 775
17 1.02833033435 131
18 1.1199639177 574
19 1.16176050466 624
20 1.07907222484 219


In [25]:
for case in validationCases:
    save_case(case)

In [27]:
predict_and_plot3d('071')

--------------------------------------------------
Loading and Preparing the data
Original input shape (300, 195, 230)
Padded input shape: (388, 283, 318)
# of parts 7 7 6
number of tiles: 120 
data shape (120, 148, 148, 148)
Original input shape (300, 195, 230)
Padded input shape: (388, 283, 318)
# of parts 7 7 6
number of tiles: 120 
data shape (120, 148, 148, 148)


100%|██████████| 120/120 [00:00<00:00, 1157049.38it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (120, 148, 148, 148, 2)
Feature shape:  (120, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 36.cpkt


100%|██████████| 120/120 [00:58<00:00,  2.15it/s]


prediction shape: (120, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 318)
# of parts 7 7 6
# of subvolumes merged:  120
(array([0, 1, 2, 3, 4, 5, 6], dtype=uint16), array([13428109,    20812,     5193,      521,      206,       96,       63]))
(300, 195, 230)
Number of regions: 92
1 0.98763646574 51
2 1.02812529399 105
3 1.04107969125 72
4 1.0012851112 121
5 1.05151365476 109
6 1.12319180549 1009
7 1.10252404356 853
8 1.09312485648 217
9 0.9555976602 124
10 2.89284458249 1270
11 1.17048515054 933
12 1.00609381915 85
13 1.08516779962 181
14 1.0064805911 101
15 1.03475136384 132
16 1.2745450089 239
17 1.13800702657 369
18 1.09530288982 285
19 1.32960747025 306
20 1.1024755718 655
21 1.09802860691 278
22 3.37097576361 2096
23 1.14908229273 507
24 0.994609393359 130
25 1.08047846948 276
26 1.1048067992 746
27 0.924951826031 54
28 0.961881228976 73
29 1.07492767629 88
30 2.90763647956 481
31 1.04583439235 226
32 1.182