In [2]:
%matplotlib inline
from fns import *
from syntheticdata import synthetic_generation
# import ipyvolume

In [3]:
import plotly
plotly.tools.set_credentials_file(username='gpernelle', api_key='4KIdNJBBApIeebdKxyN9')
import plotly.plotly as py
import plotly.graph_objs as go


In [4]:
def dice(logits, labels):
        flat_logits = logits.flatten()
        flat_labels = labels.flatten()
        intersection = np.sum(flat_logits*flat_labels)
        union = np.sum(flat_logits) + np.sum(flat_labels)
        loss = 1 - 2 * intersection / union
        return loss

### Predict

In [5]:
def predict_case(caseNumber):
    case=str(caseNumber)
    image_name = '/home/gp1514/SSD/preprocessed_data/LabelMapsNEW2_1.00-1.00-1.00_split2/%s/case.nrrd'%case
    label_name = '/home/gp1514/SSD/preprocessed_data/LabelMapsNEW2_1.00-1.00-1.00/%s/needles.nrrd'%case

    data, options_ = nrrd.read(image_name)
    data = data.astype(np.float32)
    data1, options = nrrd.read(image_name.replace('_split2', ''))
    data1 = data1.astype(np.float32)

    label_data, options_ = nrrd.read(label_name)

    prediction = predict([data1,data], "./models/unet_trained_mix_dropout-05-clahe30_f32")
    return label_data, prediction, options


def save_case(caseNumber):
    case=str(caseNumber)
    image_name = '/home/gp1514/SSD/preprocessed_data/LabelMapsNEW2_1.00-1.00-1.00_split2/%s/case.nrrd'%case
    data1, options = nrrd.read(image_name.replace('_split2', ''))
    data1 = data1.astype(np.float32)
    nrrd.write('predictions/case_%s.nrrd'%str(caseNumber), data1, options=options)



In [9]:
def predict_and_save(caseNumber):
    label_data, prediction, options = predict_case(caseNumber)
    dice(prediction, label_data)
    islands = post_processing(prediction, min_area=int(50), max_residual=float(4))
    nrrd.write('predictions/%s.nrrd'%str(caseNumber), islands, options=options)

def predict_and_plot3d(caseNumber):
    label_data, prediction, options = predict_case(caseNumber)
    dice(prediction, label_data)
    islands = post_processing(prediction, min_area=int(100), max_residual=float(4))
    nrrd.write('predictions/%s.nrrd'%str(caseNumber), islands, options=options)
    x,y,z = np.where(label_data == 1)
    xs,ys,zs = np.where(islands != 0)

    x,y,z = np.where(label_data == 1)
    xs,ys,zs = np.where(islands != 0)

    trace1 = go.Scatter3d(
        x=x,
        y=y,
        z=z,
        mode='markers',
        marker=dict(
            size=3,
            line=dict(
                color='green',
                width=2
            ),
            opacity=0.3
        )
    )

    trace2 = go.Scatter3d(
        x=xs,
        y=ys,
        z=zs,
        mode='markers',
        marker=dict(
            color='red',
            size=3,
            symbol='circle',
            line=dict(
                color='rgb(204, 204, 204)',
                width=1
            ),
            opacity=0.3
        )
    )
    data = [trace1, trace2]
    layout = go.Layout(
        title=str(caseNumber),
        margin=dict(
            l=0,
            r=0,
            b=0,
            t=100
        )
    )

    fig = go.Figure(data=data, layout=layout)
    py.iplot(fig, filename=str(caseNumber))

In [7]:
validationCases = loadCases("preprocessing/validation.txt")
testingCases = loadCases("preprocessing/testing.txt")

In [9]:
validationCases

['021', '023', '037', '038', '070', '071', '072', '074', '075', '076', '077']

In [10]:
testingCases

['028', '051', '054']

In [11]:
for case in validationCases+testingCases:
    predict_and_plot3d(case)

--------------------------------------------------
Loading and Preparing the data
Original input shape (200, 200, 77)
Padded input shape: (288, 288, 165)
# of parts 5 5 3
number of tiles: 75 
data shape (75, 148, 148, 148)
Original input shape (200, 200, 77)
Padded input shape: (288, 288, 165)
# of parts 5 5 3
number of tiles: 75 
data shape (75, 148, 148, 148)


100%|██████████| 75/75 [00:00<00:00, 944663.06it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (75, 148, 148, 148, 2)
Feature shape:  (75, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 50.cpkt


100%|██████████| 75/75 [00:09<00:00,  7.70it/s]


prediction shape: (75, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (288, 288, 165)
# of parts 5 5 3
# of subvolumes merged:  75
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18], dtype=uint16), array([3074765,    2040,     726,    1056,     215,     207,     331,
            46,      44,      38,      47,      37,      55,      60,
            44,      48,      44,      85,     112]))
(200, 200, 77)
Number of regions: 37
1 1.95342312477 151
2 1.19406364806 227
3 1.14619730123 366
4 1.15749784846 247
5 1.14085874575 191
6 1.10449033882 169
7 1.09305605204 113
8 2.19508855661 246
9 1.06578685487 107
10 1.05190114476 195
11 1.05835499086 118
12 1.92607878772 341
13 1.59773998413 225
--------------------------------------------------
Loading and Preparing the data
Original input shape (200, 200, 240)
Padded input shape: (288, 288, 328)
# of parts 5 5 6
number of tiles: 125 
data shape (

100%|██████████| 125/125 [00:00<00:00, 788403.01it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (125, 148, 148, 148, 2)
Feature shape:  (125, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 50.cpkt


100%|██████████| 125/125 [00:16<00:00,  7.64it/s]


prediction shape: (125, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (288, 288, 328)
# of parts 5 5 6
# of subvolumes merged:  125
(array([0, 1, 2, 3, 4, 5, 6], dtype=uint16), array([9579306,   14756,    2310,    1369,     965,     729,     565]))
(200, 200, 240)
Number of regions: 67
1 3.78211384823 2141
2 1.29181700644 461
3 1.13741951308 220
4 1.08672351058 148
5 1.07070466014 106
6 1.03467650031 283
7 2.62782622164 722
8 1.0506065525 175
9 1.13835058213 263
10 1.08502525471 289
11 1.09582160534 284
12 2.18764155801 1114
13 3.02316533574 508
14 1.10477822656 316
15 2.75084040593 1553
16 1.10524508031 358
17 1.13106046258 264
18 1.85694822166 493
19 1.08048129799 153
20 2.91543600135 1659
21 1.10982688284 560
22 1.13111903715 335
23 1.05476950543 207
24 1.04415495507 130
25 1.21691135356 424
26 1.55592658523 480
27 1.9775188957 157
28 1.03468594507 132
29 1.78831970034 118
-------------------------------------------------

100%|██████████| 96/96 [00:00<00:00, 783371.95it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (96, 148, 148, 148, 2)
Feature shape:  (96, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 50.cpkt


100%|██████████| 96/96 [00:12<00:00,  7.68it/s]


prediction shape: (96, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 241)
# of parts 7 7 5
# of subvolumes merged:  96
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=uint16), array([8928452,   10134,    4318,    2948,    1354,     916,     795,
           260,     413,      85,     177,     354,     294]))
(300, 195, 153)
Number of regions: 77
1 1.0167895948 108
2 1.03441018098 127
3 1.04355693245 140
4 1.12715884429 192
5 1.08335145207 147
6 1.3069535606 548
7 1.14093626349 282
8 1.19328226331 133
9 1.18415175077 617
10 1.17125112054 382
11 1.09124699072 114
12 1.1399359383 703
13 1.27921295515 660
14 1.10110059338 290
15 1.16959597174 322
16 1.11493056921 169
17 1.19119655147 186
18 1.0974903578 112
19 1.11836210719 161
20 1.1268581106 152
21 1.30189633947 679
22 1.00289929718 131
23 1.20848415586 305
24 1.39734460217 242
25 1.23017872615 311
26 1.14185142157 213
27 3.37272526786 902
--------

100%|██████████| 147/147 [00:00<00:00, 961876.27it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (147, 148, 148, 148, 2)
Feature shape:  (147, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 50.cpkt


100%|██████████| 147/147 [00:19<00:00,  7.63it/s]


prediction shape: (147, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (407, 407, 216)
# of parts 7 7 4
# of subvolumes merged:  147
(array([0, 1, 2, 3, 4], dtype=uint16), array([13008376,     9082,     5701,     1260,      989]))
(319, 319, 128)
Number of regions: 39
1 1.0245349693 143
2 1.20556968915 1014
3 1.18217152899 918
4 3.06052096797 2068
5 1.13937277286 885
6 1.19835356068 855
7 1.06082426662 172
8 2.25714950007 1167
9 1.06392658291 154
10 1.13257985134 200
11 1.30148126976 316
12 1.05673152606 169
13 1.30240596805 882
--------------------------------------------------
Loading and Preparing the data
Original input shape (300, 195, 230)
Padded input shape: (388, 283, 318)
# of parts 7 7 6
number of tiles: 120 
data shape (120, 148, 148, 148)
Original input shape (300, 195, 230)
Padded input shape: (388, 283, 318)
# of parts 7 7 6
number of tiles: 120 
data shape (120, 148, 148, 148)


100%|██████████| 120/120 [00:00<00:00, 1154395.60it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (120, 148, 148, 148, 2)
Feature shape:  (120, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 50.cpkt


100%|██████████| 120/120 [00:15<00:00,  7.65it/s]


prediction shape: (120, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 318)
# of parts 7 7 6
# of subvolumes merged:  120
(array([0, 1, 2, 3, 4], dtype=uint16), array([13438003,    15537,     1051,      394,       15]))
(300, 195, 230)
Number of regions: 59
1 1.17572849735 165
2 0.996255009489 124
3 1.20051979029 220
4 1.12525175199 710
5 1.12757640128 617
6 1.15349456376 490
7 1.27658956824 287
8 1.1599595623 417
9 1.2639726879 433
10 1.11642238 409
11 1.06633612332 242
12 1.09930845054 152
13 1.18947722218 319
14 1.08111474968 274
15 1.33103174545 265
16 1.11422052245 883
17 1.09399595834 310
18 1.26113504963 1043
19 1.29501802128 542
20 1.67024902666 137
--------------------------------------------------
Loading and Preparing the data
Original input shape (300, 195, 230)
Padded input shape: (388, 283, 318)
# of parts 7 7 6
number of tiles: 120 
data shape (120, 148, 148, 148)
Original input shape (300, 195, 230)

100%|██████████| 120/120 [00:00<00:00, 939023.28it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (120, 148, 148, 148, 2)
Feature shape:  (120, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 50.cpkt


100%|██████████| 120/120 [00:15<00:00,  7.61it/s]


prediction shape: (120, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 318)
# of parts 7 7 6
# of subvolumes merged:  120
(array([0, 1, 2, 3, 4, 5, 6], dtype=uint16), array([13425250,    20833,     7906,      488,      147,      122,      254]))
(300, 195, 230)
Number of regions: 67
1 1.10094976663 270
2 1.13090289141 130
3 1.11717666466 866
4 1.14252009407 1025
5 2.69747626717 1691
6 1.18969863793 963
7 1.04843482173 137
8 1.15483879522 506
9 1.10959184441 327
10 1.1341519378 327
11 1.26736905323 424
12 1.1401923701 792
13 1.12813797646 291
14 1.26475906046 155
15 1.13521349506 1024
16 1.13906526801 494
17 1.14618351165 690
18 1.14506294407 917
19 1.10390041993 753
20 1.14882541775 297
21 0.932077868634 108
22 1.48589031729 207
23 1.47955237507 441
24 1.26515671352 149
25 1.22634934475 315
26 3.33912887747 480
--------------------------------------------------
Loading and Preparing the data
Original input shape (3

100%|██████████| 96/96 [00:00<00:00, 680157.41it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (96, 148, 148, 148, 2)
Feature shape:  (96, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 50.cpkt


100%|██████████| 96/96 [00:12<00:00,  7.63it/s]


prediction shape: (96, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 280)
# of parts 7 7 5
# of subvolumes merged:  96
(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=uint16), array([11203033,    18812,     8297,      660,      939,       84,
            100,       47,       28]))
(300, 195, 192)
Number of regions: 74
1 0.985525972755 103
2 1.12239065855 255
3 1.12775265131 154
4 3.67541290997 2358
5 1.16277439246 939
6 1.05617383283 106
7 1.14045334489 826
8 1.13251995034 174
9 1.15905355161 931
10 1.54029740174 947
11 1.05408389051 105
12 1.13161948139 945
13 1.12540056669 428
14 1.12028345744 185
15 1.09259958909 459
16 1.12295385638 155
17 1.16461708162 431
18 1.14577806639 1014
19 1.12623609854 323
20 1.15154868824 422
21 1.14246848874 909
22 1.19803119819 542
23 1.17044221826 1086
24 1.28199218604 724
25 1.15703996561 846
26 1.12568842779 738
27 1.12378387574 841
28 1.02521171327 133
29 1.20508566403 922
30 1.1276

100%|██████████| 120/120 [00:00<00:00, 837465.02it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (120, 148, 148, 148, 2)
Feature shape:  (120, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 50.cpkt


100%|██████████| 120/120 [00:15<00:00,  7.61it/s]


prediction shape: (120, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 292)
# of parts 7 7 5
# of subvolumes merged:  120
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=uint16), array([11905545,    16055,     5895,     4117,     1161,      200,
            227,      193,      153,      132,      138,      127,       57]))
(300, 195, 204)
Number of regions: 154
1 3.17723896122 547
2 3.51782743546 866
3 1.90490041565 532
4 2.51547514321 603
5 1.0584957925 112
6 2.00420792025 346
7 1.07909655399 137
8 1.14692576754 226
9 1.1923847713 232
10 1.11640992291 134
11 1.62191059734 282
12 1.21548075584 964
13 0.963337157686 213
14 2.49609752956 873
15 1.21419954609 533
16 1.59106061679 338
17 1.09798999533 186
18 1.16107557529 317
19 1.1712117245 637
20 1.2596749204 492
21 1.17599857348 477
22 1.03108171591 154
23 1.34403072038 494
24 1.17257211327 312
25 0.954240787507 135
26 1.08319967218 207
27 1.21527

100%|██████████| 96/96 [00:00<00:00, 1051313.80it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (96, 148, 148, 148, 2)
Feature shape:  (96, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 50.cpkt


100%|██████████| 96/96 [00:12<00:00,  7.64it/s]


prediction shape: (96, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 267)
# of parts 7 7 5
# of subvolumes merged:  96
(array([0, 1, 2, 3], dtype=uint16), array([10462270,     7571,     1583,       76]))
(300, 195, 179)
Number of regions: 54
1 1.06591878145 218
2 0.963283341137 107
3 1.17706141546 929
4 1.13587575812 886
5 1.06061372495 116
6 1.06363236573 105
7 1.07423139787 113
8 2.50033708168 1329
9 2.75167829813 1994
10 2.5205819111 2248
11 1.22201305647 103
12 1.05902346586 109
13 1.1376818083 119
--------------------------------------------------
Loading and Preparing the data
Original input shape (300, 195, 179)
Padded input shape: (388, 283, 267)
# of parts 7 7 5
number of tiles: 96 
data shape (96, 148, 148, 148)
Original input shape (300, 195, 179)
Padded input shape: (388, 283, 267)
# of parts 7 7 5
number of tiles: 96 
data shape (96, 148, 148, 148)


100%|██████████| 96/96 [00:00<00:00, 951898.78it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (96, 148, 148, 148, 2)
Feature shape:  (96, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 50.cpkt


100%|██████████| 96/96 [00:12<00:00,  7.64it/s]


prediction shape: (96, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 267)
# of parts 7 7 5
# of subvolumes merged:  96
(array([0, 1, 2, 3, 4, 5, 6], dtype=uint16), array([10450571,    14176,     6192,      130,      360,       21,       50]))
(300, 195, 179)
Number of regions: 95
1 2.06597406916 338
2 2.46441309179 495
3 1.43905430233 126
4 1.07005147533 157
5 1.11412249202 322
6 1.05194106195 131
7 1.02028258139 101
8 1.06789197587 114
9 3.81551363988 2105
10 3.58175232703 2378
11 1.17460039862 117
12 1.17923682792 109
13 1.8659179252 1012
14 1.16846389063 191
15 1.22043131509 147
16 1.2271112286 111
17 2.43152535402 1652
18 1.09158251692 131
19 1.09458625475 272
20 1.29836767066 1250
21 1.87964742758 228
22 1.16463504505 158
23 1.14627459393 311
24 1.32991211937 329
25 1.04275305739 223
--------------------------------------------------
Loading and Preparing the data
Original input shape (300, 195, 166)
Padded i

100%|██████████| 96/96 [00:00<00:00, 684784.33it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (96, 148, 148, 148, 2)
Feature shape:  (96, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 50.cpkt


100%|██████████| 96/96 [00:12<00:00,  7.65it/s]


prediction shape: (96, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 254)
# of parts 7 7 5
# of subvolumes merged:  96
(array([0, 1, 2, 3, 4, 5], dtype=uint16), array([9701335,    7087,    2013,     466,      95,       4]))
(300, 195, 166)
Number of regions: 51
1 1.83199243929 211
2 1.32285395361 410
3 1.29860601195 167
4 1.49736061807 283
5 1.01106651181 113
6 1.09285266398 572
7 1.14531630966 608
8 2.1734208164 666
9 1.0340549465 192
10 1.14002887186 583
11 1.12461882468 527
12 1.04224932332 122
13 1.30223425174 118
14 1.03267489441 134
15 2.80876019311 1023
--------------------------------------------------
Loading and Preparing the data
Original input shape (220, 220, 204)
Padded input shape: (308, 308, 292)
# of parts 6 6 5
number of tiles: 125 
data shape (125, 148, 148, 148)
Original input shape (220, 220, 204)
Padded input shape: (308, 308, 292)
# of parts 6 6 5
number of tiles: 125 
data shape (125, 148, 

100%|██████████| 125/125 [00:00<00:00, 696265.60it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (125, 148, 148, 148, 2)
Feature shape:  (125, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 50.cpkt


100%|██████████| 125/125 [00:16<00:00,  7.59it/s]


prediction shape: (125, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (308, 308, 292)
# of parts 6 6 5
# of subvolumes merged:  125
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20], dtype=uint16), array([9836580,   27917,    5700,    2851,     287,     111,      26,
            15,      20,       5,       8,       7,      11,       8,
             5,      14,      10,      11,       9,       4,       1]))
(220, 220, 204)
Number of regions: 110
1 1.77723383929 144
2 1.62832085586 424
3 1.14549163852 430
4 1.22560324983 731
5 1.18001525696 461
6 0.941220091684 146
7 1.23994715054 235
8 1.16306576291 242
9 0.941640894851 103
10 1.13951170132 816
11 2.90934554628 1755
12 1.21082931059 1109
13 1.08101478359 451
14 1.11062452316 359
15 1.14277973818 407
16 1.1458260046 890
17 2.12656988334 1235
18 1.13876498162 543
19 1.14050790664 814
20 1.90197197845 368
21 1.65353948458 799
22 1

100%|██████████| 96/96 [00:00<00:00, 1043142.96it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (96, 148, 148, 148, 2)
Feature shape:  (96, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 50.cpkt


100%|██████████| 96/96 [00:12<00:00,  7.64it/s]


prediction shape: (96, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 279)
# of parts 7 7 5
# of subvolumes merged:  96
(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=uint16), array([11150415,    12091,     4096,     1835,     3933,      325,
            290,      241,      274]))
(300, 195, 191)
Number of regions: 81
1 1.03343090045 123
2 1.03114576436 195
3 1.04743753705 125
4 0.994366664807 115
5 1.36676942471 436
6 1.13147616748 689
7 1.1050956066 636
8 1.09286734849 733
9 1.05699926888 118
10 1.13335967557 217
11 1.40865109766 211
12 1.10609625808 131
13 1.12703160351 151
14 2.72812415791 1640
15 1.12807101017 945
16 1.17602572917 224
17 1.21702241685 209
18 1.09851920765 113
19 1.09038612617 111
20 1.45498828814 858
21 1.11322601571 287
22 1.06841589094 116
--------------------------------------------------
Loading and Preparing the data
Original input shape (319, 319, 220)
Padded input shape: (407, 407, 308)
# of

100%|██████████| 245/245 [00:00<00:00, 1063772.75it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (245, 148, 148, 148, 2)
Feature shape:  (245, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 50.cpkt


100%|██████████| 245/245 [00:32<00:00,  7.53it/s]


prediction shape: (245, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (407, 407, 308)
# of parts 7 7 6
# of subvolumes merged:  245
(array([0, 1, 2, 3], dtype=uint16), array([22376283,    10969,       50,      118]))
(319, 319, 220)
Number of regions: 44
1 2.21699926633 260
2 1.11507041178 507
3 1.02636334125 145
4 2.43138594818 1223
5 2.35602087299 954
6 1.09287907791 162
7 1.06297751986 159
8 1.09400983021 133
9 1.13027008748 731
10 1.1309131292 724
11 3.90014135853 1977
12 1.6243117554 445
13 1.17151150116 812
14 1.0891173995 423
15 1.22177081367 685
16 1.07443959932 226
17 1.16609511569 672
18 1.13606916751 219


In [16]:
for case in testingCases:
    predict_and_save(case)

--------------------------------------------------
Loading and Preparing the data
Original input shape (220, 220, 204)
Padded input shape: (308, 308, 292)
# of parts 6 6 5
number of tiles: 125 
data shape (125, 148, 148, 148)
Original input shape (220, 220, 204)
Padded input shape: (308, 308, 292)
# of parts 6 6 5
number of tiles: 125 
data shape (125, 148, 148, 148)


100%|██████████| 125/125 [00:00<00:00, 825650.39it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (125, 148, 148, 148, 2)
Feature shape:  (125, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 5.cpkt


100%|██████████| 125/125 [00:56<00:00,  2.50it/s]


prediction shape: (125, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (308, 308, 292)
# of parts 6 6 5
# of subvolumes merged:  125
(array([0, 1, 2, 3, 4, 5, 6], dtype=uint16), array([9847801,   21688,    2651,    1436,      21,       2,       1]))
(220, 220, 204)
Number of regions: 95
1 2.38153956868 381
2 1.093609769 273
3 1.1228390753 212
4 1.13250899646 354
5 1.25116053618 814
6 1.07114313448 317
7 1.1181439722 192
8 1.24653381678 228
9 1.08702711799 776
10 1.72090621128 1207
11 1.09295215791 375
12 1.20499343663 1107
13 1.11291849487 362
14 1.08349993003 445
15 1.03702757345 160
16 1.12289795898 398
17 1.12680020226 692
18 2.28234143434 1233
19 2.80049928738 840
20 1.11545556484 811
21 1.67531219544 704
22 1.24011093843 938
23 1.21915449635 115
24 1.15467514923 1156
25 0.94662267129 79
26 2.71464288086 1396
27 1.12917407491 112
28 1.08665784329 70
29 1.13586822945 702
30 1.10940461747 1050
31 2.59732949841 2336
32 1.020

100%|██████████| 96/96 [00:00<00:00, 131543.02it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (96, 148, 148, 148, 2)
Feature shape:  (96, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 5.cpkt


100%|██████████| 96/96 [00:42<00:00,  2.57it/s]


prediction shape: (96, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 279)
# of parts 7 7 5
# of subvolumes merged:  96
(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=uint16), array([11158612,     8700,     2678,     1089,     2254,       94,
             38,       26,        9]))
(300, 195, 191)
Number of regions: 43
1 1.12683864877 153
2 0.914007488551 93
3 1.35710348167 474
4 0.989136649154 64
5 1.11355326443 620
6 1.08622545468 574
7 1.07895610794 444
8 1.00882147404 76
9 1.06264432326 126
10 1.11084522808 196
11 1.34581191833 110
12 1.05179604345 61
13 1.08288343321 110
14 1.00166375313 86
15 2.8502815031 1815
16 1.12036773585 802
17 1.11824762619 805
18 1.17280033792 766
19 1.07847369018 828
20 0.948846526053 67
21 1.02577706719 113
--------------------------------------------------
Loading and Preparing the data
Original input shape (319, 319, 220)
Padded input shape: (407, 407, 308)
# of parts 7 7 6
number of ti

100%|██████████| 245/245 [00:00<00:00, 1102579.91it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (245, 148, 148, 148, 2)
Feature shape:  (245, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 5.cpkt


100%|██████████| 245/245 [01:40<00:00,  2.59it/s]


prediction shape: (245, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (407, 407, 308)
# of parts 7 7 6
# of subvolumes merged:  245
(array([0, 1, 2, 3], dtype=uint16), array([22377834,     9440,       36,      110]))
(319, 319, 220)
Number of regions: 35
1 2.75415777664 440
2 0.958465043059 74
3 1.05409727428 190
4 1.01509114766 132
5 2.16910435777 1096
6 1.12314136338 333
7 1.07016822832 134
8 1.07382002294 137
9 1.00608888793 95
10 1.10937917918 582
11 1.06624199159 119
12 1.09510772297 619
13 0.964160450633 64
14 1.12418258231 683
15 1.10125371609 736
16 1.15520018706 775
17 1.02833033435 131
18 1.1199639177 574
19 1.16176050466 624
20 1.07907222484 219


In [25]:
for case in validationCases:
    save_case(case)

In [27]:
predict_and_plot3d('071')

--------------------------------------------------
Loading and Preparing the data
Original input shape (300, 195, 230)
Padded input shape: (388, 283, 318)
# of parts 7 7 6
number of tiles: 120 
data shape (120, 148, 148, 148)
Original input shape (300, 195, 230)
Padded input shape: (388, 283, 318)
# of parts 7 7 6
number of tiles: 120 
data shape (120, 148, 148, 148)


100%|██████████| 120/120 [00:00<00:00, 1157049.38it/s]

--------------------------------------------------
Starting the segmenter.


imgs shape (120, 148, 148, 148, 2)
Feature shape:  (120, 148, 148, 148, 2)
INFO:tensorflow:Restoring parameters from ./models/unet_trained_mix_dropout-05-clahe30_f32/model 36.cpkt


100%|██████████| 120/120 [00:58<00:00,  2.15it/s]


prediction shape: (120, 1, 60, 60, 60, 1)
Merging subvolumes
--------------------------------------------------
Padded input shape: (388, 283, 318)
# of parts 7 7 6
# of subvolumes merged:  120
(array([0, 1, 2, 3, 4, 5, 6], dtype=uint16), array([13428109,    20812,     5193,      521,      206,       96,       63]))
(300, 195, 230)
Number of regions: 92
1 0.98763646574 51
2 1.02812529399 105
3 1.04107969125 72
4 1.0012851112 121
5 1.05151365476 109
6 1.12319180549 1009
7 1.10252404356 853
8 1.09312485648 217
9 0.9555976602 124
10 2.89284458249 1270
11 1.17048515054 933
12 1.00609381915 85
13 1.08516779962 181
14 1.0064805911 101
15 1.03475136384 132
16 1.2745450089 239
17 1.13800702657 369
18 1.09530288982 285
19 1.32960747025 306
20 1.1024755718 655
21 1.09802860691 278
22 3.37097576361 2096
23 1.14908229273 507
24 0.994609393359 130
25 1.08047846948 276
26 1.1048067992 746
27 0.924951826031 54
28 0.961881228976 73
29 1.07492767629 88
30 2.90763647956 481
31 1.04583439235 226
32 1.182